# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cfdc591bcb40e39d9cb007402534b7e54cae7792d59aa2809623ae689ba87ba27cf4e5bca9e4523c821a16f5db898e49b9de8c09f711e18bd2e25e9daa406d9f

test:
  secret_key_base: 57daf9baff7f052d29d45a493ff06abef5a846106345226e58f0c64b10e52e84b35c3e6e1d88c5e48b9f0351d2a762365bd853d3197c9ee816bb83c5dd2daaca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
